services:
  - type: web
    name: feedbackfinder-api
    env: python
    buildCommand: "pip install -r requirements.txt && ./setup.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:5000"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    region: oregon

  - type: web
    name: feedbackfinder-ui
    env: python
    buildCommand: "pip install -r requirements.txt && ./setup.sh"
    startCommand: "streamlit run main.py --server.port 8501"
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
    plan: free
    region: oregon
